### ISSUE TITLE
Component Status Report Available not Set Automatically

### ISSUE THREAD

**Issue by mcjaeger** [siemens/sw360portal#1]
It is about the clearing status of a release.

When a clearing report has been uploaded, the user must set the clearing status to report available of the release manually. It would be good to have this automatically set once an attachment exists with type of clearing report.

For example, when (AND semantics)

a) a release is updated with a new attachment of type clearing report,
-> status is "available"
b) an approver has approved this item
-> status is "approved" [1]
 then, the clearing status field of the release could be set automatically accordingly.

[1] requires new status in thrift, components.thrift, for example:
enum ClearingState {
    NEW_CLEARING = 0,
    SENT_TO_FOSSOLOGY = 1,
    UNDER_CLEARING = 2,
    REPORT_AVAILABLE = 3,
    APPROVED= 4,
}

**Comment by sw360-green-developer** [comment]
The clearing state should also be set automatically when an attachment is deleted 
Clearing state is set by the following rule:
a) if no attachment of type Clearing Report is left after change, then clearing state is NEW_CLEARING
b) if at least one Clearing Report with Check Status ACCEPTED is left, then clearing state is set to APPROVED
c) if at least one Clearing Report is left, but none with Check Status ACCEPTED, then clearing state is set to REPORT_AVAILABLE.
