### ISSUE TITLE
Vendor portlet is broken

### ISSUE THREAD

**Issue by maximilianhuber** [siemens/sw360portal#124]
#### Problem:
on current master (5d521b5ab31bcf106cf5e1d65daa354f3da3fe2e, clean vagrant build) is the vendor portlet broken.

#### What was done:
**1.** installation and setup on new box
**2.** log in as `admin`
**3.** go to vendor portlet ([.../group/guest/vendors](https://localhost:8443/group/guest/vendors))

**Situation:** At this point everything looks fine, i.e. an empty table is shown.

**4.** create an arbitrary vendor
**5.** go back to vendor portlet ([.../group/guest/vendors](https://localhost:8443/group/guest/vendors))

**Situation:** Now there is now table rendered at all (see screenshot).

#### other observations
In the search portlet one is able to find the created vendor and also the data in the database looks fine.

The problem might be, that there is a problem with `PortletURL`, i.e.
```
vendors:51 Uncaught TypeError: Cannot read property 'createURL' of undefined
```

in the code 
```javascript
50:    function createUrl_comp( paramId, paramVal) {
51:        var portletURL = Liferay.PortletURL.createURL( baseUrl ).setParameter(pageName,pageEdit).setParameter(paramId,paramVal);
52:        return portletURL.toString();
53:    }
```

--
The vendor portlet without list:
![tmp](https://cloud.githubusercontent.com/assets/1187050/13803794/dc0665f2-eb47-11e5-9fa0-de297e0b5250.png)
--
The error mentioned above:
![tmp](https://cloud.githubusercontent.com/assets/1187050/13803926/ea5f9af0-eb48-11e5-862e-d3925316125a.png)

**Comment by heydenreich** [comment]
Solved the problem by replacing
 `$(window).load(function() {
        createVendorsTable();
    });`
`function createUrl_comp( paramId, paramVal) {
        var portletURL = Liferay.PortletURL.createURL( baseUrl ).setParameter(pageName,pageEdit).setParameter(paramId,paramVal);
        return portletURL.toString();
    }`

by 
`var PortletURL;
    AUI().use('liferay-portlet-url', function (A) {
        PortletURL = Liferay.PortletURL;
        createVendorsTable()
    });

    function createUrl_comp( paramId, paramVal) {
        var portletURL = PortletURL.createURL( baseUrl ).setParameter(pageName,pageEdit).setParameter(paramId,paramVal);
        return portletURL.toString();
    } `

The Liferay.PortletURL was not defined at the moment the vendor table was build.
