### ISSUE TITLE
notification for moderation request

### ISSUE THREAD

**Issue by heydenreich** [siemens/sw360portal#36]
When a user receives a moderation request, this request must be visible in the liferay-notifications/requests.
Furthermore, the user should get sent an email with the notification.

It could involve other long running tasks in general.

**Comment by heydenreich** [comment]
Let us not use the liferay notification function, since installing the notifications portlet is obviously responsible for liferay destroying its own source code. Mailing can be better implemented using javax.mail/com.sun.mail.

Moderation requests should be sent to moderators upon creation/update o  f moderation requests, and to users when their moderation request is handled.

**Comment by mcjaeger** [comment]
There seems to be a setting needed for SMTP server without TLS, from catalina log:
` 2016-02-23 14:46:51 ERROR MailUtil:98 - Can't send command to SMTP host`

could we try to add another setting to the list of the configurable options?

More here:

http://stackoverflow.com/questions/6740838/javamail-issue-cant-send-command-to-smtp-host

**Comment by sw360-blue-developer** [comment]
I have checked the a former implementation and found only small differences:
your code:
```Java
        Properties properties = System.getProperties(); 
 
         // Setup mail server 
         properties.setProperty("mail.smtp.host", host); 
         properties.setProperty("mail.smtp.port", port); 
         properties.setProperty("mail.smtp.auth", isAuthenticationNecessary); 
         properties.setProperty("mail.smtp.starttls.enable", enableStarttls); 
 
         if (Boolean.parseBoolean(isAuthenticationNecessary)) { 
             Authenticator auth = new SMTPAuthenticator(login, password); 
             session = Session.getInstance(properties, auth); 
         } else { 
             session = Session.getDefaultInstance(properties); 
         } 
```

code from a former implementation:
```Java
			Properties props = new Properties();
			props.setProperty("mail.transport.protocol", "smtp");
			props.setProperty("mail.host", host);
			props.setProperty("mail.smtp.port", port);
			Session mailSession = null;
			if (StringUtils.isNotEmpty(username) && StringUtils.isNotEmpty(password)) {
				Authenticator authenticator = new Authenticator(username, password);
				props.setProperty("mail.smtp.submitter", authenticator.getPasswordAuthentication().getUserName());
				props.setProperty("mail.smtp.auth", "true");
				mailSession = Session.getInstance(props, authenticator);
			} else {
				mailSession = Session.getDefaultInstance(props, null);
			}
```

and we used no TLS and no special FROM email adress
