### ISSUE TITLE
Check if Attachment manipulation respects modification rights

### ISSUE THREAD

**Issue by mcjaeger** [siemens/sw360portal#47]
There are modification rights w.r.t. moderators and creators (a.k.a. owner)  of a components or release or project. 

See this wiki page for documentation: https://github.com/siemens/sw360portal/wiki/Dev-Role-Authorisation-Model

**Comment by joshovi** [comment]
As far as we know, this feature is not yet implement and need more efforts.
On a rough technical scale, there is a few step that need to be done.
1. Create a new view in couchdb that links attachments to the corresponding release/component (see http://localhost:5984/_utils/database.html?sw360db/_design/Component/_view/usedAttachmentContents)
2. Create a new method in the AttachmentService "bool canUserAccessAttachment(1: User user, 2: string attachmentId);"
3. Implement this method in AttachmentHandler, the method should check the business logic (see documentation) and check that the given user is allowed to download the attachment, considering its rights with the corresponding object owner
4. In the attachment portlet, in the method that serves attachment, call the backend first to check that the user is allowed to download. Serve only if allowed.

**Comment by heydenreich** [comment]
1. Remove delete attachments from non-edit modus.
2. check access rights -> moderation request.
