### ISSUE TITLE
paging @ admin portlets

### ISSUE THREAD

**Issue by sw360-blue-developer** [siemens/sw360portal#81]
all admin portlets with lists should get a paging like the component list portlet

**Comment by mcjaeger** [comment]
All admin developers is maybe must for a pull request, let segment it and follow an order in case.

1. db sanitation (chosen also to cover the database topic)
2. bulk release edit
3. users
4 ...

Paging should like on the entry / main view of components or projects: like just have a simple pages list. Optionally keyword filtering on the left (as it is there)

**Comment by sw360-green-developer** [comment]
Do you think keyword filtering is necessary for Bulk Release Edit? I am in doubt.

Regarding keyword filtering in users. There are two user tables. Should I filter both tables using one filter input field, or have two separate filters? I prefer a single filter as the tables contain essentially the same kind of data and if you're looking for a particular person, you may not know in which table she is.

I think keyword filtering on db sanitation page is unnecessary.  Agree/disagree?

**Comment by sw360-green-developer** [comment]
assuming the answers are no, yes, and agree, this can be reviewed in branch dev/pagingAdminPortlets

**Comment by mcjaeger** [comment]
(nice) I would have voted:
- more a yes than no because it is now that look against 1000 dataset and then trying to find the page on which the openssl is in is maybe cumber some.
- yes
- agree

I will have a look at the branch.

**Comment by sw360-green-developer** [comment]
I'm going to add the filter to bulk release edit meanwhile.

**Comment by sw360-green-developer** [comment]
Added keyword filtering. A known bug is that editing a row, does not change its sort order or filtering unless the whole page is reloaded. I suggest we leave it like this for now and fix later if it turns out to be annoying.
